# Generated by Django 6.0.4 on 2026-05-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_notifications_options_friend_requests_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='user',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='friend',
            new_name='user2',
        ),
    ]
