# Generated by Django 6.0.4 on 2026-05-23 10:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/do8c7jwpb/image/upload/v1779531900/default-profile-picture-avatar-photo-placeholder-vector-illustration-default-profile-picture-avatar-photo-placeholder-vector-189495158_vt4mtz.webp', max_length=255, verbose_name='image'),
        ),
    ]
