# Generated by Django 6.0.4 on 2026-05-24 08:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
