# Generated by Django 6.0.4 on 2026-05-24 11:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_group_chat_image_messages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='gpfp',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/do8c7jwpb/image/upload/v1779531900/default-profile-picture-avatar-photo-placeholder-vector-illustration-default-profile-picture-avatar-photo-placeholder-vector-189495158_vt4mtz.webp', max_length=255, verbose_name='image'),
        ),
    ]
