# Generated by Django 6.0.4 on 2026-05-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='friend_requests',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
